/*
================================================================
AIDRONE — MASTER ENGINEERING PARAMETERS
FILE 00 / 24

PURPOSE
-------
Single source of truth for global geometry and system constraints.

NO printable geometry is generated by this file.

Coordinate system:
    Origin      = vehicle geometric center
    +Z          = upward / inlet direction
    -Z          = nominal thrust exhaust direction
    X,Y         = equatorial plane

Units:
    distance    = mm
    angle       = degrees
    mass        = grams unless explicitly stated otherwise

Architecture:
    115 mm spherical companion drone
    70 mm protected aerodynamic core
================================================================
*/


// ============================================================
// 1. OPENSCAD RESOLUTION
// ============================================================

$fn = 100;


// ============================================================
// 2. VEHICLE GLOBAL ENVELOPE
// ============================================================

VEHICLE_OD = 115.0;

VEHICLE_RADIUS =
    VEHICLE_OD / 2;


// Absolute external keep-out

VEHICLE_X_MIN = -VEHICLE_RADIUS;
VEHICLE_X_MAX =  VEHICLE_RADIUS;

VEHICLE_Y_MIN = -VEHICLE_RADIUS;
VEHICLE_Y_MAX =  VEHICLE_RADIUS;

VEHICLE_Z_MIN = -VEHICLE_RADIUS;
VEHICLE_Z_MAX =  VEHICLE_RADIUS;


// ============================================================
// 3. CRASH-CAGE ENVELOPE
// ============================================================

SHELL_WALL = 2.0;

SHELL_OD = VEHICLE_OD;

SHELL_ID =
    SHELL_OD -
    2 * SHELL_WALL;

SHELL_OUTER_RADIUS =
    SHELL_OD / 2;

SHELL_INNER_RADIUS =
    SHELL_ID / 2;


// Expected:
//
// OD = 115
// ID = 111
//
// Outer radius = 57.5
// Inner radius = 55.5


// ============================================================
// 4. AERODYNAMIC CORE
// ============================================================

AIRWAY_DIAMETER = 70.0;

AIRWAY_RADIUS =
    AIRWAY_DIAMETER / 2;


// IMPORTANT:
//
// r < 35 mm is a HARD AERODYNAMIC KEEP-OUT.
//
// Electronics, batteries, cameras, wiring and shell members
// may not enter this cylindrical volume through the active
// propulsion region.


DUCT_WALL = 2.0;

DUCT_OUTER_RADIUS =
    AIRWAY_RADIUS +
    DUCT_WALL;

DUCT_OD =
    DUCT_OUTER_RADIUS * 2;


// Expected:
//
// airway = 70 mm
// duct OD = 74 mm


DUCT_LENGTH = 70.0;

DUCT_Z_MIN =
    -DUCT_LENGTH / 2;

DUCT_Z_MAX =
     DUCT_LENGTH / 2;


// ============================================================
// 5. ELECTRONICS PACKAGING ANNULUS
// ============================================================

// At Z=0:
//
// shell inner radius = 55.5
// duct outer radius  = 37.0
//
// therefore maximum theoretical radial packaging depth:
//
// 55.5 - 37 = 18.5 mm


EQUATORIAL_PACKAGING_DEPTH =
    SHELL_INNER_RADIUS -
    DUCT_OUTER_RADIUS;


// Function giving internal spherical radius at a given Z.
//
// Sphere:
//
//      r² + z² = R²
//
// therefore:
//
//      r = sqrt(R²-z²)


function shell_available_radius(z) =

    abs(z) <= SHELL_INNER_RADIUS

    ? sqrt(
        SHELL_INNER_RADIUS *
        SHELL_INNER_RADIUS
        -
        z * z
      )

    : 0;


// Available electronics depth outside duct at Z.

function packaging_depth(z) =

    max(
        0,

        shell_available_radius(z)
        -
        DUCT_OUTER_RADIUS
    );


// ============================================================
// 6. PROPULSION DESIGN ENVELOPE
// ============================================================

/*
The rotor is NOT defined as a printable propeller yet.

These values define only the permissible swept-volume envelope.

70 mm duct
68 mm preliminary maximum rotor diameter

=> nominal static radial clearance:

    (70 - 68) / 2 = 1 mm

Actual rotor geometry will be selected after propulsion
analysis.
*/


ROTOR_MAX_DIAMETER = 68.0;

ROTOR_MAX_RADIUS =
    ROTOR_MAX_DIAMETER / 2;


ROTOR_STATIC_TIP_CLEARANCE =

    AIRWAY_RADIUS -
    ROTOR_MAX_RADIUS;


// ============================================================
// 7. VANE SYSTEM
// ============================================================

VANE_COUNT = 4;

VANE_MAX_DEFLECTION = 25;

VANE_MIN_DEFLECTION =
    -VANE_MAX_DEFLECTION;


// Final vane dimensions intentionally NOT defined here.
//
// They must be produced by the control-authority calculations.


// ============================================================
// 8. CAMERA ARCHITECTURE
// ============================================================

CAMERA_COUNT = 4;

CAMERA_ANGLE_STEP =
    360 / CAMERA_COUNT;


// RunCam Nano 4 nominal body

CAMERA_BODY_X = 14.0;
CAMERA_BODY_Y = 14.0;
CAMERA_BODY_Z = 14.0;


// CAD cavity target

CAMERA_POCKET_X = 14.2;
CAMERA_POCKET_Y = 14.2;


// Camera pocket depth retained from packaging requirement

CAMERA_POCKET_DEPTH = 15.0;


// Nominal camera body mass

CAMERA_MASS_G = 2.9;


// Total camera mass before wiring

CAMERA_TOTAL_MASS_G =
    CAMERA_COUNT *
    CAMERA_MASS_G;


// Approximate published field of view

CAMERA_FOV_DEG = 155;


// ============================================================
// 9. MASS ARCHITECTURE
// ============================================================

/*
Three mass limits:

TARGET:
    engineering objective

DESIGN:
    physics calculations should work at this mass

HARD LIMIT:
    design is rejected if predicted mass exceeds this before
    detailed flight validation.
*/


MASS_TARGET_G = 180;

MASS_DESIGN_G = 200;

MASS_HARD_LIMIT_G = 225;


// Convert design mass to kg

MASS_DESIGN_KG =
    MASS_DESIGN_G / 1000;


// ============================================================
// 10. GRAVITY
// ============================================================

GRAVITY =
    9.80665;


// Hover thrust required in Newtons

HOVER_THRUST_N =
    MASS_DESIGN_KG *
    GRAVITY;


// ============================================================
// 11. THRUST MARGIN
// ============================================================

/*
Preliminary system requirement:

Maximum static thrust >= 2 x vehicle weight.

This is NOT a statement that normal flight occurs at 2g.

It reserves control and acceleration authority.
*/


THRUST_TO_WEIGHT_DESIGN = 2.0;


MAX_THRUST_REQUIREMENT_N =

    HOVER_THRUST_N *
    THRUST_TO_WEIGHT_DESIGN;


// ============================================================
// 12. AIR PROPERTIES
// ============================================================

// Approximate sea-level standard density

AIR_DENSITY_KG_M3 = 1.225;


// Convert airway radius mm -> metres

AIRWAY_RADIUS_M =
    AIRWAY_RADIUS /
    1000;


// Rotor/duct disk area

DISK_AREA_M2 =

    PI *
    AIRWAY_RADIUS_M *
    AIRWAY_RADIUS_M;


// ============================================================
// 13. IDEAL MOMENTUM THEORY
// ============================================================

/*
Ideal hover induced velocity:

                 T
    vi = sqrt( -------- )
               2 rho A


Ideal induced power:

    Pi = T * vi


These are LOWER-BOUND aerodynamic values.

They do NOT include:

    rotor profile drag
    duct loss
    motor loss
    ESC loss
    vane blockage
    inlet loss
    wiring loss
*/


function ideal_induced_velocity(thrust_N) =

    sqrt(
        thrust_N /
        (
            2 *
            AIR_DENSITY_KG_M3 *
            DISK_AREA_M2
        )
    );


function ideal_induced_power(thrust_N) =

    thrust_N *
    ideal_induced_velocity(thrust_N);


HOVER_IDEAL_VI_MPS =

    ideal_induced_velocity(
        HOVER_THRUST_N
    );


HOVER_IDEAL_POWER_W =

    ideal_induced_power(
        HOVER_THRUST_N
    );


MAX_IDEAL_VI_MPS =

    ideal_induced_velocity(
        MAX_THRUST_REQUIREMENT_N
    );


MAX_IDEAL_POWER_W =

    ideal_induced_power(
        MAX_THRUST_REQUIREMENT_N
    );


// ============================================================
// 14. PRINTING / MANUFACTURING RULES
// ============================================================

/*
These are prototype rules.

They are NOT precision-machining tolerances.
*/


NOZZLE_DIAMETER = 0.4;


// Preferred minimum structural member

MIN_STRUCTURAL_MEMBER =
    2.0;


// General printed sliding fit:
//
// radial clearance per mating side

PRINT_SLIDING_RADIAL_CLEARANCE =
    0.20;


// Therefore recommended DIAMETRAL clearance

PRINT_SLIDING_DIAMETRAL_CLEARANCE =
    2 *
    PRINT_SLIDING_RADIAL_CLEARANCE;


// Previous 74.0 / 74.2 interface only gives:
//
// 0.1 mm per side.
//
// We therefore DO NOT preserve that as the final production fit.
//
// New nominal collar bore:

COLLAR_BORE_DIAMETER =

    DUCT_OD +
    PRINT_SLIDING_DIAMETRAL_CLEARANCE;


// Expected:
//
// 74.0 + 0.4 = 74.4 mm


// Moving pivot clearance

PRINT_MOVING_CLEARANCE =
    0.35;


// ============================================================
// 15. FASTENER DESIGN PLACEHOLDERS
// ============================================================

/*
Actual fastener family will be selected later.

These numbers are intentionally NOT used to create final
threaded geometry.
*/

MICRO_FASTENER_NOMINAL_D =
    2.0;


// ============================================================
// 16. GLOBAL HARD DESIGN RULES
// ============================================================

/*
RULE A

No non-propulsion geometry inside:

    r < AIRWAY_RADIUS

within the active duct.


RULE B

No geometry may exceed:

    radius = VEHICLE_RADIUS


RULE C

Electronics must satisfy:

    radial_outer_edge
        <
    shell_available_radius(z)


RULE D

Camera/sensor structures may not intersect their own
field-of-view keep-outs.


RULE E

No structure may intersect the rotor swept volume.


RULE F

No structure may intersect the complete vane swept volume:

    -25 deg ... +25 deg


RULE G

Final mass must satisfy:

    mass <= MASS_HARD_LIMIT_G


RULE H

X/Y mass symmetry must be preserved unless the mass-property
solver explicitly compensates it elsewhere.
*/


// ============================================================
// 17. PARAMETER VALIDATION
// ============================================================

assert(
    VEHICLE_OD == 115,
    "Vehicle OD changed from locked 115 mm."
);


assert(
    SHELL_ID == 111,
    "Shell ID must equal 111 mm."
);


assert(
    AIRWAY_DIAMETER == 70,
    "Protected airway must remain 70 mm."
);


assert(
    DUCT_OD == 74,
    "Expected duct OD is 74 mm."
);


assert(
    ROTOR_MAX_DIAMETER <
    AIRWAY_DIAMETER,

    "Rotor envelope must be smaller than airway."
);


assert(
    ROTOR_STATIC_TIP_CLEARANCE > 0,

    "Rotor has zero/negative duct clearance."
);


assert(
    MASS_TARGET_G <= MASS_DESIGN_G,

    "Target mass cannot exceed design mass."
);


assert(
    MASS_DESIGN_G <= MASS_HARD_LIMIT_G,

    "Design mass exceeds hard mass limit."
);


assert(
    CAMERA_TOTAL_MASS_G == 11.6,

    "Camera mass calculation changed unexpectedly."
);


// ============================================================
// 18. ENGINEERING OUTPUT
// ============================================================

echo(
    "============================================"
);

echo(
    "AIDRONE MASTER PARAMETERS"
);

echo(
    "Vehicle OD mm =",
    VEHICLE_OD
);

echo(
    "Shell ID mm =",
    SHELL_ID
);

echo(
    "Airway diameter mm =",
    AIRWAY_DIAMETER
);

echo(
    "Duct OD mm =",
    DUCT_OD
);

echo(
    "Equatorial packaging depth mm =",
    EQUATORIAL_PACKAGING_DEPTH
);

echo(
    "Rotor maximum diameter mm =",
    ROTOR_MAX_DIAMETER
);

echo(
    "Rotor nominal radial clearance mm =",
    ROTOR_STATIC_TIP_CLEARANCE
);

echo(
    "Final prototype collar bore mm =",
    COLLAR_BORE_DIAMETER
);

echo(
    "Design mass g =",
    MASS_DESIGN_G
);

echo(
    "Hover thrust N =",
    HOVER_THRUST_N
);

echo(
    "Required maximum thrust N =",
    MAX_THRUST_REQUIREMENT_N
);

echo(
    "Disk area m^2 =",
    DISK_AREA_M2
);

echo(
    "Ideal hover induced velocity m/s =",
    HOVER_IDEAL_VI_MPS
);

echo(
    "Ideal hover induced power W =",
    HOVER_IDEAL_POWER_W
);

echo(
    "Ideal max-thrust induced power W =",
    MAX_IDEAL_POWER_W
);

echo(
    "Camera total mass g =",
    CAMERA_TOTAL_MASS_G
);

echo(
    "Packaging depth Z=0 mm =",
    packaging_depth(0)
);

echo(
    "Packaging depth Z=10 mm =",
    packaging_depth(10)
);

echo(
    "Packaging depth Z=20 mm =",
    packaging_depth(20)
);

echo(
    "Packaging depth Z=30 mm =",
    packaging_depth(30)
);

echo(
    "============================================"
);