/*
================================================================
AIDRONE
FILE 10 / 24
AERODYNAMIC DUCT / CENTRAL STRUCTURAL CORE

DEPENDENCIES
------------
00_master_parameters.scad
02_materials_tolerances.scad

PURPOSE
-------
Creates the central 70 mm aerodynamic passage and its
structural outer body.

GLOBAL DATUM
------------
Origin = vehicle geometric center
Z axis = propulsion axis
Z range = -35 ... +35 mm

DESIGN RULES
------------
1. Active airway remains free of electronics.
2. No flight-controller tabs enter the airway.
3. Rotor keep-out is explicit.
4. Stator interfaces are external to the airway unless
   deliberately generated by the future motor-stator file.
5. Structural interfaces are symmetric.
6. No propeller geometry is invented here.
================================================================
*/


include <00_master_parameters.scad>
include <02_materials_tolerances.scad>


$fn = 100;


// ============================================================
// LOCAL PARAMETERS
// ============================================================

DUCT_H = 70.0;

DUCT_Z0 = -DUCT_H / 2;
DUCT_Z1 =  DUCT_H / 2;


// Main aerodynamic diameter.

FLOW_D = 70.0;

FLOW_R = FLOW_D / 2;


// Structural outer diameter.

BODY_WALL = 2.0;

BODY_OD =
    FLOW_D +
    2 * BODY_WALL;

BODY_R =
    BODY_OD / 2;


// ============================================================
// INLET / OUTLET ZONES
// ============================================================

/*
The current file keeps the central passage cylindrical.

It does NOT pretend the final inlet-lip contour has already
been aerodynamically optimized.

The dedicated inlet file will later create the external lip.
*/

INLET_ZONE_H = 6.0;

OUTLET_ZONE_H = 6.0;


// ============================================================
// PROPULSION KEEP-OUT
// ============================================================

ROTOR_ENVELOPE_D = 68.0;

ROTOR_ENVELOPE_R =
    ROTOR_ENVELOPE_D / 2;


// Static radial clearance.

ROTOR_RADIAL_CLEARANCE =
    FLOW_R -
    ROTOR_ENVELOPE_R;


// ============================================================
// TWO ROTOR-STAGE STUDY POSITIONS
// ============================================================

/*
These are AXIAL ENVELOPE positions only.

They do not claim final motor/rotor spacing.

Positive Z = upper stage
Negative Z = lower stage
*/

ROTOR_A_Z = 12.0;

ROTOR_B_Z = -12.0;


// Axial swept-envelope thickness used only for visualization.

ROTOR_KEEP_OUT_H = 4.0;


// ============================================================
// STRUCTURAL COLLAR INTERFACE
// ============================================================

/*
Four external anti-rotation rails.

These never penetrate the airway.
*/

KEY_COUNT = 4;

KEY_ANGLE_OFFSET = 45;

KEY_RADIAL_PROJECTION = 1.5;

KEY_TANGENTIAL_WIDTH = 3.0;

KEY_Z_LENGTH = 20.0;


// ============================================================
// EXTERNAL DATUM PADS
// ============================================================

/*
These pads provide future attachment references for the
electronics frame.

They do NOT contain final screw patterns yet.
*/

DATUM_PAD_COUNT = 4;

DATUM_PAD_ANGLE_OFFSET = 0;

DATUM_PAD_RADIAL_LENGTH = 3.0;

DATUM_PAD_TANGENTIAL_WIDTH = 6.0;

DATUM_PAD_Z_HEIGHT = 4.0;


// ============================================================
// DEBUG DISPLAY
// ============================================================

SHOW_DUCT = true;

SHOW_AIRWAY_KEEP_OUT = false;

SHOW_ROTOR_KEEP_OUTS = false;

SHOW_GLOBAL_CENTER = false;


// ============================================================
// MAIN
// ============================================================

aidrone_aero_duct();


// ============================================================
// COMPLETE DUCT
// ============================================================

module aidrone_aero_duct()
{
    if (SHOW_DUCT)
    {
        union()
        {
            duct_body();

            external_alignment_keys();

            external_datum_pads();
        }
    }

    if (SHOW_AIRWAY_KEEP_OUT)
    {
        %airway_keep_out();
    }

    if (SHOW_ROTOR_KEEP_OUTS)
    {
        %rotor_keep_outs();
    }

    if (SHOW_GLOBAL_CENTER)
    {
        %global_center_marker();
    }
}


// ============================================================
// DUCT BODY
// ============================================================

module duct_body()
{
    difference()
    {
        outer_duct_body();

        aerodynamic_airway();
    }
}


// ============================================================
// OUTER DUCT BODY
// ============================================================

module outer_duct_body()
{
    translate([
        0,
        0,
        DUCT_Z0
    ])
    cylinder(
        h = DUCT_H,
        d = BODY_OD
    );
}


// ============================================================
// AERODYNAMIC AIRWAY
// ============================================================

module aerodynamic_airway()
{
    /*
    Extend subtraction slightly beyond both ends.

    This prevents coincident boolean faces.
    */

    boolean_eps = 0.10;

    translate([
        0,
        0,
        DUCT_Z0 - boolean_eps
    ])
    cylinder(
        h =
            DUCT_H +
            2 * boolean_eps,

        d = FLOW_D
    );
}


// ============================================================
// HARD AIRWAY KEEP-OUT
// ============================================================

module airway_keep_out()
{
    /*
    Any electronics CAD entering this volume is a design error.

    Future verification files will perform explicit
    intersections against this geometry.
    */

    translate([
        0,
        0,
        DUCT_Z0
    ])
    cylinder(
        h = DUCT_H,
        d = FLOW_D
    );
}


// ============================================================
// ROTOR SWEPT-VOLUME KEEP-OUT
// ============================================================

module rotor_keep_out(
    z_position
)
{
    translate([
        0,
        0,
        z_position
    ])
    cylinder(
        h = ROTOR_KEEP_OUT_H,
        d = ROTOR_ENVELOPE_D,
        center = true
    );
}


module rotor_keep_outs()
{
    rotor_keep_out(
        ROTOR_A_Z
    );

    rotor_keep_out(
        ROTOR_B_Z
    );
}


// ============================================================
// EXTERNAL ALIGNMENT KEYS
// ============================================================

module external_alignment_keys()
{
    for (
        i = [
            0 :
            KEY_COUNT - 1
        ]
    )
    {
        angle =
            KEY_ANGLE_OFFSET +
            i *
            360 /
            KEY_COUNT;

        rotate([
            0,
            0,
            angle
        ])
        translate([
            BODY_R - 0.05,
            -KEY_TANGENTIAL_WIDTH / 2,
            -KEY_Z_LENGTH / 2
        ])
        cube([
            KEY_RADIAL_PROJECTION + 0.05,
            KEY_TANGENTIAL_WIDTH,
            KEY_Z_LENGTH
        ]);
    }
}


// ============================================================
// EXTERNAL ELECTRONICS DATUM PADS
// ============================================================

module external_datum_pads()
{
    for (
        i = [
            0 :
            DATUM_PAD_COUNT - 1
        ]
    )
    {
        angle =
            DATUM_PAD_ANGLE_OFFSET +
            i *
            360 /
            DATUM_PAD_COUNT;

        rotate([
            0,
            0,
            angle
        ])
        translate([
            BODY_R - 0.05,
            -DATUM_PAD_TANGENTIAL_WIDTH / 2,
            -DATUM_PAD_Z_HEIGHT / 2
        ])
        cube([
            DATUM_PAD_RADIAL_LENGTH + 0.05,
            DATUM_PAD_TANGENTIAL_WIDTH,
            DATUM_PAD_Z_HEIGHT
        ]);
    }
}


// ============================================================
// GLOBAL CENTER MARKER
// ============================================================

module global_center_marker()
{
    marker_length = 10;
    marker_d = 0.5;

    // X

    rotate([
        0,
        90,
        0
    ])
    cylinder(
        h = marker_length,
        d = marker_d,
        center = true
    );

    // Y

    rotate([
        90,
        0,
        0
    ])
    cylinder(
        h = marker_length,
        d = marker_d,
        center = true
    );

    // Z

    cylinder(
        h = marker_length,
        d = marker_d,
        center = true
    );
}


// ============================================================
// GEOMETRIC VALIDATION
// ============================================================

assert(
    FLOW_D == 70,
    "FAIL: airway diameter must remain 70 mm."
);


assert(
    BODY_OD == 74,
    "FAIL: duct body OD must remain 74 mm."
);


assert(
    DUCT_H == 70,
    "FAIL: duct height must remain 70 mm."
);


assert(
    DUCT_Z0 == -35,
    "FAIL: duct must begin at Z=-35."
);


assert(
    DUCT_Z1 == 35,
    "FAIL: duct must end at Z=+35."
);


assert(
    ROTOR_ENVELOPE_D <
    FLOW_D,

    "FAIL: rotor envelope exceeds airway."
);


assert(
    ROTOR_RADIAL_CLEARANCE >=
    MIN_ROTOR_STATIC_RADIAL_CLEARANCE,

    "FAIL: rotor static radial clearance below manufacturing rule."
);


assert(
    abs(ROTOR_A_Z) +
    ROTOR_KEEP_OUT_H / 2
    <
    DUCT_H / 2,

    "FAIL: upper rotor envelope exits duct."
);


assert(
    abs(ROTOR_B_Z) +
    ROTOR_KEEP_OUT_H / 2
    <
    DUCT_H / 2,

    "FAIL: lower rotor envelope exits duct."
);


// ============================================================
// ENGINEERING OUTPUT
// ============================================================

echo(
    "============================================"
);

echo(
    "AIDRONE FILE 10 — AERODYNAMIC DUCT"
);

echo(
    "Airway diameter =",
    FLOW_D
);

echo(
    "Outer diameter =",
    BODY_OD
);

echo(
    "Wall =",
    BODY_WALL
);

echo(
    "Height =",
    DUCT_H
);

echo(
    "Z min =",
    DUCT_Z0
);

echo(
    "Z max =",
    DUCT_Z1
);

echo(
    "Rotor envelope diameter =",
    ROTOR_ENVELOPE_D
);

echo(
    "Rotor static radial clearance =",
    ROTOR_RADIAL_CLEARANCE
);

echo(
    "Rotor A study Z =",
    ROTOR_A_Z
);

echo(
    "Rotor B study Z =",
    ROTOR_B_Z
);

echo(
    "Maximum key radius =",
    BODY_R +
    KEY_RADIAL_PROJECTION
);

echo(
    "Maximum datum-pad radius =",
    BODY_R +
    DATUM_PAD_RADIAL_LENGTH
);

echo(
    "============================================"
);